basepath = "."

locales = [
    "es",
    "fr",
    "zh-CN",
]

[[paths]]
    reference = "frontend/public/static/locale/en-US/*.ftl"
    l10n = "frontend/public/static/locale/{locale}/*.ftl"
